/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Résumé des AgendaEntry d\'un reminder (générées à la création ou à la modification)
 */
export interface AgendaGenerationSummaryDTO { 
    /**
     * Nombre d\'entrées d\'agenda liées au reminder
     */
    nombre?: number;
    /**
     * Date/heure de la première entrée (null si aucune)
     */
    premiereDate?: string;
    /**
     * Date/heure de la dernière entrée (null si aucune)
     */
    derniereDate?: string;
}

