/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Membre de la famille
 */
export interface FamilyMemberDTO { 
    id?: number;
    nom?: string;
    couleur?: string;
    /**
     * Personnage (avatar) : configuration libre du catalogue front, absente = avatar par défaut
     */
    avatarConfig?: { [key: string]: any | null; } | null;
}

