/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Prévision d\'une journée et tenue conseillée
 */
export interface MeteoJourDTO { 
    date?: string;
    /**
     * État du ciel, simplifié depuis le code météo WMO
     */
    ciel?: MeteoJourDTO.CielEnum;
    /**
     * Température minimale (°C)
     */
    temperatureMin?: number | null;
    /**
     * Température maximale (°C)
     */
    temperatureMax?: number | null;
    /**
     * Température ressentie à l\'heure de départ (°C)
     */
    ressentiMatin?: number | null;
    /**
     * Température ressentie maximale entre 10 h et 18 h (°C)
     */
    ressentiJournee?: number | null;
    /**
     * Risque de pluie maximal entre l\'heure de départ et 18 h (%)
     */
    risquePluie?: number | null;
    /**
     * Tenue conseillée, dans l\'ordre d\'affichage
     */
    tenue?: Array<MeteoJourDTO.TenueEnum>;
    /**
     * Plus chaud l\'après-midi : prévoir un pull qu\'on pourra enlever
     */
    superposer?: boolean;
}
export namespace MeteoJourDTO {
    export const CielEnum = {
        Soleil: 'SOLEIL',
        Eclaircies: 'ECLAIRCIES',
        Nuageux: 'NUAGEUX',
        Brouillard: 'BROUILLARD',
        Bruine: 'BRUINE',
        Pluie: 'PLUIE',
        Neige: 'NEIGE',
        Orage: 'ORAGE',
    } as const;
    export type CielEnum = typeof CielEnum[keyof typeof CielEnum];
    export const TenueEnum = {
        TShirt: 'T_SHIRT',
        Pull: 'PULL',
        Veste: 'VESTE',
        Manteau: 'MANTEAU',
        Impermeable: 'IMPERMEABLE',
        Short: 'SHORT',
        Pantalon: 'PANTALON',
        Bonnet: 'BONNET',
        Echarpe: 'ECHARPE',
        Gants: 'GANTS',
        Bottes: 'BOTTES',
        Casquette: 'CASQUETTE',
        CremeSolaire: 'CREME_SOLAIRE',
    } as const;
    export type TenueEnum = typeof TenueEnum[keyof typeof TenueEnum];
}


