/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Résumé d\'un mois
 */
export interface MonthSummaryDTO { 
    /**
     * Numéro du mois (1-12)
     */
    mois?: number;
    /**
     * Nombre total d\'entrées du mois
     */
    total?: number;
    /**
     * Nombre d\'entrées par type (types absents = 0)
     */
    parType?: { [key: string]: number; };
}

