/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Article du garde-manger : toujours à la maison
 */
export interface PantryItemDTO { 
    id?: number;
    nom?: string;
}

