/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Ligne d\'ingrédient d\'une recette. L\'ingrédient est désigné par son nom : créé s\'il n\'existe pas encore.
 */
export interface RecipeIngredientRequest { 
    nom: string;
    quantite: number;
    unite: RecipeIngredientRequest.UniteEnum;
}
export namespace RecipeIngredientRequest {
    export const UniteEnum = {
        G: 'G',
        Kg: 'KG',
        Ml: 'ML',
        L: 'L',
        Piece: 'PIECE',
        CuillereSoupe: 'CUILLERE_SOUPE',
        CuillereCafe: 'CUILLERE_CAFE',
        Boite: 'BOITE',
        Sachet: 'SACHET',
        Pincee: 'PINCEE',
    } as const;
    export type UniteEnum = typeof UniteEnum[keyof typeof UniteEnum];
}


