/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Ingrédient d\'une recette, avec sa quantité
 */
export interface RecipeIngredientDTO { 
    ingredientId?: number;
    nom?: string;
    rayon?: RecipeIngredientDTO.RayonEnum | null;
    quantite?: number;
    unite?: RecipeIngredientDTO.UniteEnum;
}
export namespace RecipeIngredientDTO {
    export const RayonEnum = {
        FruitsLegumes: 'FRUITS_LEGUMES',
        BoucheriePoissonnerie: 'BOUCHERIE_POISSONNERIE',
        Cremerie: 'CREMERIE',
        Epicerie: 'EPICERIE',
        Surgeles: 'SURGELES',
        Boulangerie: 'BOULANGERIE',
        Boissons: 'BOISSONS',
        Autre: 'AUTRE',
    } as const;
    export type RayonEnum = typeof RayonEnum[keyof typeof RayonEnum];
    export const UniteEnum = {
        G: 'G',
        Kg: 'KG',
        Ml: 'ML',
        L: 'L',
        Piece: 'PIECE',
        CuillereSoupe: 'CUILLERE_SOUPE',
        CuillereCafe: 'CUILLERE_CAFE',
        Boite: 'BOITE',
        Sachet: 'SACHET',
        Pincee: 'PINCEE',
    } as const;
    export type UniteEnum = typeof UniteEnum[keyof typeof UniteEnum];
}


