/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Règle de récurrence d\'un reminder
 */
export interface RecurrenceRuleDTO { 
    frequence?: RecurrenceRuleDTO.FrequenceEnum;
    intervalle?: number;
    joursSemaine?: Array<RecurrenceRuleDTO.JoursSemaineEnum>;
    dateFin?: string;
    nombreOccurrences?: number;
}
export namespace RecurrenceRuleDTO {
    export const FrequenceEnum = {
        Daily: 'DAILY',
        Weekly: 'WEEKLY',
        Monthly: 'MONTHLY',
        Yearly: 'YEARLY',
    } as const;
    export type FrequenceEnum = typeof FrequenceEnum[keyof typeof FrequenceEnum];
    export const JoursSemaineEnum = {
        Monday: 'MONDAY',
        Tuesday: 'TUESDAY',
        Wednesday: 'WEDNESDAY',
        Thursday: 'THURSDAY',
        Friday: 'FRIDAY',
        Saturday: 'SATURDAY',
        Sunday: 'SUNDAY',
    } as const;
    export type JoursSemaineEnum = typeof JoursSemaineEnum[keyof typeof JoursSemaineEnum];
}


