/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Règle de récurrence. Fin : dateFin OU nombreOccurrences (pas les deux) ; aucune des deux = sans fin.
 */
export interface RecurrenceRuleRequest { 
    /**
     * Fréquence
     */
    frequence: RecurrenceRuleRequest.FrequenceEnum;
    /**
     * Tous les N jours/semaines/mois/ans (défaut 1)
     */
    intervalle?: number;
    /**
     * Jours de la semaine (WEEKLY uniquement). Vide = jour de la date de début.
     */
    joursSemaine?: Array<RecurrenceRuleRequest.JoursSemaineEnum>;
    /**
     * Dernière date incluse de la récurrence
     */
    dateFin?: string;
    /**
     * Nombre total d\'occurrences (la première comprise)
     */
    nombreOccurrences?: number;
}
export namespace RecurrenceRuleRequest {
    export const FrequenceEnum = {
        Daily: 'DAILY',
        Weekly: 'WEEKLY',
        Monthly: 'MONTHLY',
        Yearly: 'YEARLY',
    } as const;
    export type FrequenceEnum = typeof FrequenceEnum[keyof typeof FrequenceEnum];
    export const JoursSemaineEnum = {
        Monday: 'MONDAY',
        Tuesday: 'TUESDAY',
        Wednesday: 'WEDNESDAY',
        Thursday: 'THURSDAY',
        Friday: 'FRIDAY',
        Saturday: 'SATURDAY',
        Sunday: 'SUNDAY',
    } as const;
    export type JoursSemaineEnum = typeof JoursSemaineEnum[keyof typeof JoursSemaineEnum];
}


