/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgendaGenerationSummaryDTO } from './agenda-generation-summary-dto';
import { ReminderDTO } from './reminder-dto';


/**
 * Reminder créé/modifié + résumé des AgendaEntry générées
 */
export interface ReminderWithAgendaDTO { 
    reminder?: ReminderDTO;
    /**
     * Résumé des entrées d\'agenda liées au reminder
     */
    agenda?: AgendaGenerationSummaryDTO;
}

