/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoutineStepRequest } from './routine-step-request';


/**
 * Création / modification d\'une routine (les étapes sont remplacées par la liste donnée)
 */
export interface RoutineRequest { 
    /**
     * Membre (création uniquement ; ignoré en modification)
     */
    membreId?: number;
    nom: string;
    sousTitre?: string;
    type: RoutineRequest.TypeEnum;
    theme: RoutineRequest.ThemeEnum;
    /**
     * Jours où la routine est proposée
     */
    jours: Array<RoutineRequest.JoursEnum>;
    heureDebut?: string | null;
    heureFin?: string | null;
    /**
     * Absent = active
     */
    active?: boolean;
    etapes?: Array<RoutineStepRequest>;
}
export namespace RoutineRequest {
    export const TypeEnum = {
        Morning: 'MORNING',
        Evening: 'EVENING',
        Custom: 'CUSTOM',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const ThemeEnum = {
        Day: 'DAY',
        Night: 'NIGHT',
    } as const;
    export type ThemeEnum = typeof ThemeEnum[keyof typeof ThemeEnum];
    export const JoursEnum = {
        Monday: 'MONDAY',
        Tuesday: 'TUESDAY',
        Wednesday: 'WEDNESDAY',
        Thursday: 'THURSDAY',
        Friday: 'FRIDAY',
        Saturday: 'SATURDAY',
        Sunday: 'SUNDAY',
    } as const;
    export type JoursEnum = typeof JoursEnum[keyof typeof JoursEnum];
}


