/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Copier un modèle de routine chez un membre
 */
export interface RoutineFromTemplateRequest { 
    /**
     * matin ou soir
     */
    modele: string;
    /**
     * Langue des libellés : fr ou nl
     */
    langue: string;
}

