/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoutineStepDTO } from './routine-step-dto';
import { RoutineRunDTO } from './routine-run-dto';


/**
 * Routine d\'un membre, avec son état pour le jour demandé
 */
export interface RoutineDTO { 
    id?: number;
    membreId?: number;
    nom?: string;
    sousTitre?: string | null;
    type?: RoutineDTO.TypeEnum;
    theme?: RoutineDTO.ThemeEnum;
    /**
     * Jours où la routine est proposée
     */
    jours?: Array<RoutineDTO.JoursEnum>;
    /**
     * Début de la plage horaire indicative
     */
    heureDebut?: string | null;
    heureFin?: string | null;
    /**
     * Désactivée = cachée à l\'enfant
     */
    active?: boolean;
    /**
     * Ordre d\'affichage parmi les routines du membre
     */
    position?: number;
    etapes?: Array<RoutineStepDTO>;
    /**
     * État du jour demandé
     */
    etat?: RoutineRunDTO;
}
export namespace RoutineDTO {
    export const TypeEnum = {
        Morning: 'MORNING',
        Evening: 'EVENING',
        Custom: 'CUSTOM',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const ThemeEnum = {
        Day: 'DAY',
        Night: 'NIGHT',
    } as const;
    export type ThemeEnum = typeof ThemeEnum[keyof typeof ThemeEnum];
    export const JoursEnum = {
        Monday: 'MONDAY',
        Tuesday: 'TUESDAY',
        Wednesday: 'WEDNESDAY',
        Thursday: 'THURSDAY',
        Friday: 'FRIDAY',
        Saturday: 'SATURDAY',
        Sunday: 'SUNDAY',
    } as const;
    export type JoursEnum = typeof JoursEnum[keyof typeof JoursEnum];
}


