/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoutineStepDTO } from './routine-step-dto';


/**
 * Modèle de routine prêt à l\'emploi, copié (modifiable) chez un membre
 */
export interface RoutineTemplateDTO { 
    id?: string;
    nom?: string;
    sousTitre?: string;
    type?: RoutineTemplateDTO.TypeEnum;
    theme?: RoutineTemplateDTO.ThemeEnum;
    etapes?: Array<RoutineStepDTO>;
}
export namespace RoutineTemplateDTO {
    export const TypeEnum = {
        Morning: 'MORNING',
        Evening: 'EVENING',
        Custom: 'CUSTOM',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const ThemeEnum = {
        Day: 'DAY',
        Night: 'NIGHT',
    } as const;
    export type ThemeEnum = typeof ThemeEnum[keyof typeof ThemeEnum];
}


