/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Étape d\'une routine
 */
export interface RoutineStepDTO { 
    id?: number;
    /**
     * Ordre (0 = première étape)
     */
    position?: number;
    libelle?: string;
    /**
     * Illustration du catalogue du front
     */
    icone?: string;
    /**
     * Couleur pastel de la ligne
     */
    couleur?: string;
}

