/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Statuts à changer ; un champ absent reste inchangé
 */
export interface ShoppingItemStatusRequest { 
    /**
     * Coché en magasin
     */
    achete?: boolean | null;
    /**
     * Déjà à la maison : exclu des achats
     */
    aLaMaison?: boolean | null;
}

