/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Repas à l\'origine d\'une ligne générée (« pour : lasagnes lundi »)
 */
export interface ShoppingItemSourceDTO { 
    /**
     * Id du repas au moment de la génération (il a pu être supprimé depuis)
     */
    repasId?: number;
    date?: string;
    creneau?: ShoppingItemSourceDTO.CreneauEnum;
    /**
     * Nom de la recette
     */
    titre?: string;
}
export namespace ShoppingItemSourceDTO {
    export const CreneauEnum = {
        PetitDejeuner: 'PETIT_DEJEUNER',
        Midi: 'MIDI',
        Souper: 'SOUPER',
    } as const;
    export type CreneauEnum = typeof CreneauEnum[keyof typeof CreneauEnum];
}


