/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Période des repas à prendre en compte (jours inclus)
 */
export interface ShoppingListGenerateRequest { 
    dateDebut: string;
    dateFin: string;
}

