/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Article ajouté ou modifié à la main. Quantité et unité facultatives ; pas d\'unité sans quantité.
 */
export interface ShoppingItemRequest { 
    nom: string;
    quantite?: number | null;
    unite?: ShoppingItemRequest.UniteEnum | null;
}
export namespace ShoppingItemRequest {
    export const UniteEnum = {
        G: 'G',
        Kg: 'KG',
        Ml: 'ML',
        L: 'L',
        Piece: 'PIECE',
        CuillereSoupe: 'CUILLERE_SOUPE',
        CuillereCafe: 'CUILLERE_CAFE',
        Boite: 'BOITE',
        Sachet: 'SACHET',
        Pincee: 'PINCEE',
    } as const;
    export type UniteEnum = typeof UniteEnum[keyof typeof UniteEnum];
}


