/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShoppingItemSourceDTO } from './shopping-item-source-dto';


/**
 * Ligne de la liste de courses
 */
export interface ShoppingItemDTO { 
    id?: number;
    nom?: string;
    /**
     * Absente pour un article sans quantité
     */
    quantite?: number | null;
    unite?: ShoppingItemDTO.UniteEnum | null;
    /**
     * Rayon de l\'ingrédient, s\'il est connu
     */
    rayon?: ShoppingItemDTO.RayonEnum | null;
    /**
     * GENERE (depuis les repas) ou MANUEL
     */
    origine?: ShoppingItemDTO.OrigineEnum;
    /**
     * Coché en magasin
     */
    achete?: boolean;
    /**
     * Déjà à la maison : exclu des achats
     */
    aLaMaison?: boolean;
    /**
     * Ligne générée modifiée à la main : la régénération garde sa quantité
     */
    modifie?: boolean;
    /**
     * Repas qui utilisent cet ingrédient (vide pour un article manuel)
     */
    sources?: Array<ShoppingItemSourceDTO>;
}
export namespace ShoppingItemDTO {
    export const UniteEnum = {
        G: 'G',
        Kg: 'KG',
        Ml: 'ML',
        L: 'L',
        Piece: 'PIECE',
        CuillereSoupe: 'CUILLERE_SOUPE',
        CuillereCafe: 'CUILLERE_CAFE',
        Boite: 'BOITE',
        Sachet: 'SACHET',
        Pincee: 'PINCEE',
    } as const;
    export type UniteEnum = typeof UniteEnum[keyof typeof UniteEnum];
    export const RayonEnum = {
        FruitsLegumes: 'FRUITS_LEGUMES',
        BoucheriePoissonnerie: 'BOUCHERIE_POISSONNERIE',
        Cremerie: 'CREMERIE',
        Epicerie: 'EPICERIE',
        Surgeles: 'SURGELES',
        Boulangerie: 'BOULANGERIE',
        Boissons: 'BOISSONS',
        Autre: 'AUTRE',
    } as const;
    export type RayonEnum = typeof RayonEnum[keyof typeof RayonEnum];
    export const OrigineEnum = {
        Genere: 'GENERE',
        Manuel: 'MANUEL',
    } as const;
    export type OrigineEnum = typeof OrigineEnum[keyof typeof OrigineEnum];
}


