/**
 * Agenda familial - API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonthSummaryDTO } from './month-summary-dto';


/**
 * Vue annuelle : nombre d\'entrées par mois, groupées par type
 */
export interface YearSummaryDTO { 
    annee?: number;
    /**
     * Nombre total d\'entrées de l\'année
     */
    total?: number;
    /**
     * 12 éléments, de janvier à décembre
     */
    mois?: Array<MonthSummaryDTO>;
}

