-- Schéma de l'agenda tel que Hibernate le créait avant l'introduction de Flyway (ddl-auto=update).
-- SQL portable H2 / PostgreSQL : enums en varchar + check. Les noms des clés étrangères sont ceux générés
-- par Hibernate, pour qu'une base neuve soit identique à une base existante (reprise en version 1 par
-- baseline-on-migrate, sans rejouer ce script).

create table family_member (
    couleur varchar(7) not null,
    id bigint generated by default as identity,
    nom varchar(100) not null,
    primary key (id)
);

create table recurrence_rule (
    date_fin date,
    intervalle integer not null,
    nombre_occurrences integer,
    id bigint generated by default as identity,
    frequence varchar(10) not null check (frequence in ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY')),
    primary key (id)
);

create table recurrence_rule_jours (
    recurrence_rule_id bigint not null,
    jour varchar(10) check (jour in ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    unique (recurrence_rule_id, jour)
);

create table reminder (
    actif boolean not null,
    recurring boolean not null,
    date_heure_debut timestamp(6) not null,
    date_heure_fin timestamp(6),
    id bigint generated by default as identity,
    recurrence_rule_id bigint unique,
    type varchar(20) not null check (type in ('SPORT', 'TEST_MEDICAL', 'RENDEZ_VOUS', 'AUTRE')),
    titre varchar(200) not null,
    description varchar(2000),
    primary key (id)
);

create table reminder_membres (
    member_id bigint not null,
    reminder_id bigint not null,
    primary key (member_id, reminder_id)
);

create table agenda_entry (
    date_heure timestamp(6) not null,
    id bigint generated by default as identity,
    reminder_id bigint not null,
    statut varchar(10) not null check (statut in ('PREVU', 'COMPLETE', 'ANNULE', 'DEPLACE')),
    primary key (id),
    constraint uk_agenda_entry_reminder_date unique (reminder_id, date_heure)
);

create index idx_agenda_entry_date on agenda_entry (date_heure);

alter table agenda_entry
    add constraint FKpg3tpvj4v28x936jyjqlv0fq foreign key (reminder_id) references reminder;

alter table recurrence_rule_jours
    add constraint FKolylfyojmyv0hpiv9c6jmw4a9 foreign key (recurrence_rule_id) references recurrence_rule;

alter table reminder
    add constraint FKlmwfqc4akfnt6og9l646bry06 foreign key (recurrence_rule_id) references recurrence_rule;

alter table reminder_membres
    add constraint FK1cv2g4sjb2jsp00ef5eeubihl foreign key (member_id) references family_member;

alter table reminder_membres
    add constraint FKjttkolba8apk4k0uqeoxg6qh9 foreign key (reminder_id) references reminder;
