-- Repas de la semaine et recettes types. Les ingrédients sont partagés entre recettes (future liste de courses).

create table ingredient (
    id bigint generated by default as identity,
    nom varchar(100) not null,
    nom_normalise varchar(100) not null,
    rayon varchar(30) check (rayon in ('FRUITS_LEGUMES', 'BOUCHERIE_POISSONNERIE', 'CREMERIE', 'EPICERIE',
                                        'SURGELES', 'BOULANGERIE', 'BOISSONS', 'AUTRE')),
    primary key (id),
    constraint uk_ingredient_nom_normalise unique (nom_normalise)
);

create table recipe (
    id bigint generated by default as identity,
    nom varchar(150) not null,
    description varchar(500),
    portions integer not null check (portions > 0),
    temps_preparation integer,
    instructions varchar(10000),
    primary key (id)
);

create table recipe_ingredient (
    id bigint generated by default as identity,
    recipe_id bigint not null,
    ingredient_id bigint not null,
    position integer not null,
    quantite numeric(10, 3) not null check (quantite > 0),
    unite varchar(20) not null check (unite in ('G', 'KG', 'ML', 'L', 'PIECE', 'CUILLERE_SOUPE', 'CUILLERE_CAFE',
                                                 'BOITE', 'SACHET', 'PINCEE')),
    primary key (id),
    constraint fk_recipe_ingredient_recipe foreign key (recipe_id) references recipe (id),
    constraint fk_recipe_ingredient_ingredient foreign key (ingredient_id) references ingredient (id)
);

create index idx_recipe_ingredient_recipe on recipe_ingredient (recipe_id);
create index idx_recipe_ingredient_ingredient on recipe_ingredient (ingredient_id);

create table meal (
    id bigint generated by default as identity,
    date_repas date not null,
    creneau varchar(20) not null check (creneau in ('PETIT_DEJEUNER', 'MIDI', 'SOUPER')),
    portions integer not null check (portions > 0),
    recipe_id bigint,
    libelle varchar(100),
    primary key (id),
    constraint uk_meal_date_creneau unique (date_repas, creneau),
    -- une recette OU un libellé libre, jamais les deux ni aucun
    constraint ck_meal_recette_ou_libelle check ((recipe_id is null and libelle is not null)
                                              or (recipe_id is not null and libelle is null)),
    constraint fk_meal_recipe foreign key (recipe_id) references recipe (id)
);

create index idx_meal_recipe on meal (recipe_id);
