-- Liste de courses (une seule, partagée par la famille) et garde-manger.

-- Période de la dernière génération : une seule ligne (id = 1).
create table shopping_list (
    id bigint not null,
    date_debut date not null,
    date_fin date not null,
    genere_le timestamp not null,
    primary key (id),
    constraint ck_shopping_list_unique check (id = 1)
);

create table shopping_item (
    id bigint generated by default as identity,
    nom varchar(100) not null,
    nom_normalise varchar(100) not null,
    -- facultatifs pour un article ajouté à la main (« papier toilette »)
    quantite numeric(10, 3) check (quantite > 0),
    unite varchar(20) check (unite in ('G', 'KG', 'ML', 'L', 'PIECE', 'CUILLERE_SOUPE', 'CUILLERE_CAFE',
                                        'BOITE', 'SACHET', 'PINCEE')),
    -- ingrédient connu (rayon) : toujours pour une ligne générée, si le nom correspond pour un article manuel
    ingredient_id bigint,
    origine varchar(10) not null check (origine in ('GENERE', 'MANUEL')),
    -- ligne générée : nom normalisé + famille d'unité, retrouvée d'une génération à l'autre
    cle_generation varchar(130),
    achete boolean not null default false,
    a_la_maison boolean not null default false,
    -- ligne générée supprimée ou vidée après achat : masquée tant qu'un repas en a besoin
    retire boolean not null default false,
    -- ligne générée modifiée à la main : la régénération garde son nom, sa quantité et son unité
    modifie boolean not null default false,
    primary key (id),
    constraint uk_shopping_item_cle_generation unique (cle_generation),
    constraint ck_shopping_item_unite_avec_quantite check (unite is null or quantite is not null),
    constraint ck_shopping_item_cle_si_genere check ((origine = 'GENERE') = (cle_generation is not null)),
    constraint fk_shopping_item_ingredient foreign key (ingredient_id) references ingredient (id)
);

create index idx_shopping_item_ingredient on shopping_item (ingredient_id);

-- Repas à l'origine d'une ligne générée (« pour : lasagnes lundi »). Copie, sans clé étrangère :
-- la ligne reste lisible jusqu'à la régénération suivante même si le repas est supprimé entre-temps.
create table shopping_item_source (
    shopping_item_id bigint not null,
    repas_id bigint not null,
    date_repas date not null,
    creneau varchar(20) not null check (creneau in ('PETIT_DEJEUNER', 'MIDI', 'SOUPER')),
    titre varchar(150) not null,
    constraint fk_shopping_item_source_item foreign key (shopping_item_id) references shopping_item (id)
        on delete cascade
);

create index idx_shopping_item_source_item on shopping_item_source (shopping_item_id);

-- Ingrédients qu'on a toujours à la maison : marqués « déjà à la maison » à la génération.
create table pantry_item (
    id bigint generated by default as identity,
    nom varchar(100) not null,
    nom_normalise varchar(100) not null,
    primary key (id),
    constraint uk_pantry_item_nom_normalise unique (nom_normalise)
);

insert into pantry_item (nom, nom_normalise) values
    ('Sel', 'sel'),
    ('Poivre', 'poivre'),
    ('Huile d''olive', 'huile d''olive'),
    ('Sucre', 'sucre');
