-- Routines des membres (tableaux « ma routine du matin / du soir ») et leur suivi jour par jour.

create table routine (
    id bigint generated by default as identity,
    member_id bigint not null,
    nom varchar(100) not null,
    sous_titre varchar(150),
    type varchar(10) not null check (type in ('MORNING', 'EVENING', 'CUSTOM')),
    theme varchar(10) not null check (theme in ('DAY', 'NIGHT')),
    -- plage horaire indicative (mise en avant de la routine du moment)
    heure_debut time,
    heure_fin time,
    active boolean not null default true,
    position integer not null default 0,
    primary key (id),
    constraint ck_routine_plage check ((heure_debut is null) = (heure_fin is null)),
    constraint fk_routine_member foreign key (member_id) references family_member (id) on delete cascade
);

create index idx_routine_member on routine (member_id);

create table routine_jours (
    routine_id bigint not null,
    jour varchar(10) not null check (jour in ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    constraint uk_routine_jours unique (routine_id, jour),
    constraint fk_routine_jours_routine foreign key (routine_id) references routine (id) on delete cascade
);

create table routine_step (
    id bigint generated by default as identity,
    routine_id bigint not null,
    position integer not null,
    libelle varchar(150) not null,
    -- id d'une illustration du catalogue du front
    icone varchar(40) not null,
    couleur varchar(7) not null,
    primary key (id),
    constraint fk_routine_step_routine foreign key (routine_id) references routine (id) on delete cascade
);

create index idx_routine_step_routine on routine_step (routine_id);

-- Une exécution par routine et par jour : les coches repartent de zéro chaque jour.
create table routine_run (
    id bigint generated by default as identity,
    routine_id bigint not null,
    date_run date not null,
    completed_at timestamp,
    reward_played boolean not null default false,
    primary key (id),
    constraint uk_routine_run_jour unique (routine_id, date_run),
    constraint fk_routine_run_routine foreign key (routine_id) references routine (id) on delete cascade
);

create table routine_run_step (
    routine_run_id bigint not null,
    step_id bigint not null,
    primary key (routine_run_id, step_id),
    constraint fk_routine_run_step_run foreign key (routine_run_id) references routine_run (id) on delete cascade,
    constraint fk_routine_run_step_step foreign key (step_id) references routine_step (id) on delete cascade
);
