export * from './agenda.service';
import { AgendaService } from './agenda.service';
export * from './courses.service';
import { CoursesService } from './courses.service';
export * from './garde-manger.service';
import { GardeMangerService } from './garde-manger.service';
export * from './ingredients.service';
import { IngredientsService } from './ingredients.service';
export * from './membres.service';
import { MembresService } from './membres.service';
export * from './meteo.service';
import { MeteoService } from './meteo.service';
export * from './recettes.service';
import { RecettesService } from './recettes.service';
export * from './reminders.service';
import { RemindersService } from './reminders.service';
export * from './repas.service';
import { RepasService } from './repas.service';
export const APIS = [AgendaService, CoursesService, GardeMangerService, IngredientsService, MembresService, MeteoService, RecettesService, RemindersService, RepasService];
